#pragma once

// Use public generated headers from https://github.com/PoomSmart/YouTubeHeader
// Expect the repo to be checked out at ./YouTubeHeader in CI/local builds
#import "YouTubeHeader/YTAlertView.h"
#import "YouTubeHeader/YTIGuideResponse.h"
#import "YouTubeHeader/YTIGuideResponseSupportedRenderers.h"
#import "YouTubeHeader/YTIPivotBarSupportedRenderers.h"
#import "YouTubeHeader/YTIPivotBarRenderer.h"
#import "YouTubeHeader/YTIBrowseRequest.h"
#import "YouTubeHeader/YTISectionListRenderer.h"
#import "YouTubeHeader/YTISectionListSupportedRenderers.h"
#import "YouTubeHeader/YTIItemSectionRenderer.h"
#import "YouTubeHeader/YTIItemSectionSupportedRenderers.h"
#import "YouTubeHeader/YTQTMButton.h"
#import "YouTubeHeader/YTIButtonRenderer.h"
#import "YouTubeHeader/YTVideoQualitySwitchOriginalController.h"
#import "YouTubeHeader/YTWatchController.h"
#import "YouTubeHeader/YTPlayerOverlay.h"
#import "YouTubeHeader/YTPlayerOverlayProvider.h"
#import "YouTubeHeader/YTSettingsViewController.h"
#import "YouTubeHeader/YTSettingsSectionItem.h"
#import "YouTubeHeader/YTSettingsSectionItemManager.h"
#import "YouTubeHeader/YTSettingsPickerViewController.h"
#import "YouTubeHeader/YTUIUtils.h"
#import "YouTubeHeader/YTIMenuConditionalServiceItemRenderer.h"
#import "YouTubeHeader/YTToastResponderEvent.h"
#import "YouTubeHeader/YTPageStyleController.h"
#import "YouTubeHeader/ASCollectionElement.h"
#import "YouTubeHeader/ASCollectionView.h"
#import "YouTubeHeader/ELMNodeController.h"